# 使用语言
language: node_js
# node版本
node_js: stable
# 设置只监听哪个分支
branches:
  only:
  - source

cache:
  apt: true
  yarn: true
  directories:
    - node_modules
    
# tarvis生命周期执行顺序详见官网文档
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
- git config --global user.name "fydy"
- git config --global user.email "edu@yuns.me"
- yarn add hexo-cli deasync mathjax-node-page hexo-generator-sitemap hexo-generator-baidu-sitemap hexo-sliding-spoiler hexo-symbols-count-time hexo-wordcount gitalk gulp-minify-css gulp-uglify gulp-htmlmin gulp-htmlclean gulp hexo-neat hexo-service-worker hexo-filter-optimize --save

script:
- hexo clean
- hexo g
after_success:
- cd ./public
- git init
- git add --all .
- git commit -m "yunxi"
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
# Coding Pages
- git push --force --quiet "https://deweke:${CO_TOKEN}@${CO_REF}" master:master
# Gitlab Pages
- git push --force --quiet "https://towit:${GI_TOKEN}@${GI_REF}" master:master

env:
 global:
   # Coding Pages
   - CO_REF: git.coding.net/deweke/deweke.coding.me.git
   # Gitlab Pages
   - GI_REF: gitlab.com/towit/towit.gitlab.io.git
